spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC

  jdbc:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8085


